import {getAll,put,remove,getByIndex,addActivity} from '../db.js';
import {escapeHTML,formatDate,pageHead,openModal,confirmModal,toast,uid,sanitizeText} from '../ui.js';

const templates={checklist:{icon:'✓',description:'Lista recorrente de conferência.'},cadastro:{icon:'▦',description:'Ficha organizada de itens ou informações.'},diario:{icon:'✎',description:'Registros sucessivos com data e contexto.'},rastreador:{icon:'◎',description:'Acompanhamento de medidas, estados ou progresso.'}};
export async function renderForja(root,ctx,params){
  const modules=(await getAll('forgeModules')).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  root.innerHTML=`<section class="page">${pageHead('FORJA','Crie ferramentas pessoais sem programar uma nova página para cada necessidade.','<button id="newForgeBtn" class="btn btn-primary">+ Criar ferramenta</button>')}
    <article class="card" style="margin-bottom:16px"><div class="card-head"><h3>Como funciona</h3><span class="badge success">Construtor local</span></div><p>Escolha um modelo, defina campos e instale. A ferramenta passa a aparecer no QG e pode receber registros imediatamente.</p><div class="grid grid-4">${Object.entries(templates).map(([key,t])=>`<div class="kv"><small>${t.icon} ${key.toUpperCase()}</small><strong>${t.description}</strong></div>`).join('')}</div></article>
    <div class="grid grid-3">${modules.length?modules.map(m=>`<article class="card module-card"><span class="module-symbol">${escapeHTML(m.icon)}</span><h3>${escapeHTML(m.name)}</h3><p>${escapeHTML(m.description||templates[m.template]?.description||'Ferramenta personalizada.')}</p><div class="module-footer"><span class="badge">${m.fields.length} campos</span><div class="action-row"><button class="btn btn-secondary btn-sm" data-info="${m.id}">Detalhes</button><button class="btn btn-danger btn-sm" data-delete="${m.id}">Excluir</button></div></div></article>`).join(''):`<article class="card span-2"><div class="empty-state">A FORJA ainda está vazia. Crie uma ferramenta para uma necessidade real da sua rotina.</div></article>`}</div>
  </section>`;
  root.querySelector('#newForgeBtn').onclick=()=>newModule(ctx);
  root.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>moduleInfo(modules.find(m=>m.id===b.dataset.info)));
  root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const m=modules.find(x=>x.id===b.dataset.delete);const records=await getByIndex('forgeRecords','moduleId',m.id);if(await confirmModal('Excluir ferramenta?',`“${m.name}” e ${records.length} registro(s) serão removidos.`,'Excluir')){for(const r of records)await remove('forgeRecords',r.id);await remove('forgeModules',m.id);await addActivity('forja',`Ferramenta excluída: ${m.name}`);toast('Ferramenta excluída.');ctx.refresh();}});
  if(params?.get('action')==='new') setTimeout(()=>newModule(ctx),0);
}
function moduleInfo(m){if(!m)return;openModal(`<div class="modal-head"><div><h3>${escapeHTML(m.icon)} ${escapeHTML(m.name)}</h3><small>Criado em ${formatDate(m.createdAt)}</small></div><button class="modal-close" type="button">×</button></div><p>${escapeHTML(m.description||'Sem descrição.')}</p><h3>Campos</h3><div class="list">${m.fields.map(f=>`<div class="list-item"><div><b>${escapeHTML(f.label)}</b><small>Tipo: ${escapeHTML(f.type)}</small></div></div>`).join('')}</div><p class="section-note">Abra o QG para usar esta ferramenta e adicionar registros.</p>`);}
function fieldRow(index,label='',type='text'){return `<div class="field-row" data-field-row><label class="field"><span>Nome do campo</span><input data-field-label value="${escapeHTML(label)}" placeholder="Ex.: Quilometragem" required></label><label class="field"><span>Tipo</span><select data-field-type><option value="text" ${type==='text'?'selected':''}>Texto curto</option><option value="textarea" ${type==='textarea'?'selected':''}>Texto longo</option><option value="number" ${type==='number'?'selected':''}>Número</option><option value="date" ${type==='date'?'selected':''}>Data</option><option value="checkbox" ${type==='checkbox'?'selected':''}>Sim/Não</option></select></label><button class="btn btn-danger btn-sm" data-remove-field type="button">Remover</button></div>`;}
function presetFields(template){return {checklist:[['Item','text'],['Concluído','checkbox'],['Data','date']],cadastro:[['Nome','text'],['Descrição','textarea'],['Data','date']],diario:[['Título','text'],['Registro','textarea'],['Data','date']],rastreador:[['Indicador','text'],['Valor','number'],['Data','date'],['Observação','textarea']]}[template]||[['Nome','text']];}
function newModule(ctx){
  const modal=openModal(`<div class="modal-head"><h3>Nova ferramenta da FORJA</h3><button class="modal-close" type="button">×</button></div><form id="forgeForm"><div class="form-grid"><label class="field"><span>Nome</span><input name="name" required maxlength="70" placeholder="Ex.: Controle de pneus"></label><label class="field"><span>Modelo</span><select id="forgeTemplate" name="template">${Object.entries(templates).map(([k,v])=>`<option value="${k}">${v.icon} ${k}</option>`).join('')}</select></label><label class="field"><span>Ícone ou símbolo</span><input name="icon" maxlength="3" value="✓"></label><label class="field"><span>Descrição</span><input name="description" maxlength="150" placeholder="Finalidade da ferramenta"></label></div><div class="card-head" style="margin-top:18px"><h3>Campos</h3><button id="addFieldBtn" class="btn btn-secondary btn-sm" type="button">+ Campo</button></div><div id="fieldBuilder" class="field-builder"></div><div class="action-row" style="margin-top:16px"><button class="btn btn-primary" type="submit">Instalar ferramenta</button></div></form>`);
  const builder=modal.querySelector('#fieldBuilder'),templateSelect=modal.querySelector('#forgeTemplate'),iconInput=modal.querySelector('[name="icon"]');
  const setPreset=()=>{builder.innerHTML=presetFields(templateSelect.value).map((f,i)=>fieldRow(i,f[0],f[1])).join('');iconInput.value=templates[templateSelect.value].icon;bindRemove();};
  const bindRemove=()=>modal.querySelectorAll('[data-remove-field]').forEach(b=>b.onclick=()=>{if(modal.querySelectorAll('[data-field-row]').length<=1)return toast('Mantenha pelo menos um campo.','error');b.closest('[data-field-row]').remove();});
  templateSelect.onchange=setPreset;modal.querySelector('#addFieldBtn').onclick=()=>{builder.insertAdjacentHTML('beforeend',fieldRow(Date.now()));bindRemove();};setPreset();
  modal.querySelector('#forgeForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const rows=[...modal.querySelectorAll('[data-field-row]')];const fields=rows.map((r,i)=>({id:`field_${i+1}`,label:sanitizeText(r.querySelector('[data-field-label]').value),type:r.querySelector('[data-field-type]').value})).filter(f=>f.label);if(!fields.length)return toast('Adicione pelo menos um campo.','error');const mod={id:uid('module'),name:sanitizeText(fd.get('name')),template:sanitizeText(fd.get('template')),icon:sanitizeText(fd.get('icon'))||'✦',description:sanitizeText(fd.get('description')),fields,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await put('forgeModules',mod);await addActivity('forja',`Ferramenta criada: ${mod.name}`);modal.close();toast('Ferramenta instalada no QG.');ctx.refresh();};
}
