import {exportAll,importAll,clearAll,getAll,getSetting,setSetting,addActivity} from '../db.js';
import {configurePin} from '../security.js';
import {escapeHTML,formatDate,pageHead,downloadJSON,confirmModal,toast} from '../ui.js';

export async function renderGuardiao(root,ctx){
  const [activity,autoLock]=await Promise.all([getAll('activity'),getSetting('autoLockMinutes',5)]);activity.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  root.innerHTML=`<section class="page">${pageHead('GUARDIÃO','Controle de acesso, cópias de segurança e rastreabilidade das alterações.')}
    <div class="grid grid-2"><article class="card"><div class="card-head"><h3>PIN e bloqueio</h3><span class="badge success">Ativo</span></div><p>O PIN protege a abertura da interface neste aparelho. Ele não substitui a criptografia completa do dispositivo.</p><form id="pinForm" class="form-grid"><label class="field"><span>Novo PIN</span><input name="pin" inputmode="numeric" pattern="[0-9]*" maxlength="8" type="password" required></label><label class="field"><span>Confirmar PIN</span><input name="confirm" inputmode="numeric" pattern="[0-9]*" maxlength="8" type="password" required></label><div class="span-2 action-row"><button class="btn btn-primary" type="submit">Alterar PIN</button><button id="lockGuardianBtn" class="btn btn-secondary" type="button">Bloquear agora</button></div></form></article>
    <article class="card"><div class="card-head"><h3>Backup local</h3><span class="badge">JSON</span></div><p>Exporte antes de atualizar o GitHub, trocar de aparelho ou limpar o navegador. A restauração substitui o conteúdo atual.</p><div class="action-row"><button id="exportBtn" class="btn btn-primary">Exportar backup</button><button id="importBtn" class="btn btn-secondary">Importar backup</button></div><p class="section-note">O backup inclui o hash de verificação do PIN, não o PIN legível. Após restaurar, use o mesmo PIN do arquivo.</p></article></div>
    <div class="grid grid-2" style="margin-top:16px"><article class="card"><div class="card-head"><h3>Bloqueio automático</h3><span class="badge">${autoLock} min</span></div><form id="autoLockForm"><label class="field"><span>Tempo sem atividade</span><select name="minutes"><option value="1" ${autoLock==1?'selected':''}>1 minuto</option><option value="5" ${autoLock==5?'selected':''}>5 minutos</option><option value="15" ${autoLock==15?'selected':''}>15 minutos</option><option value="30" ${autoLock==30?'selected':''}>30 minutos</option><option value="0" ${autoLock==0?'selected':''}>Somente manual</option></select></label><button class="btn btn-secondary" style="margin-top:10px" type="submit">Salvar tempo</button></form></article><article class="card"><div class="card-head"><h3>Zona de risco</h3><span class="badge warning">Irreversível</span></div><p>Apaga todos os dados locais, inclusive PIN, memórias, decisões e ferramentas.</p><button id="resetBtn" class="btn btn-danger">Apagar tudo e reiniciar</button></article></div>
    <article class="card" style="margin-top:16px"><div class="card-head"><h3>Registro de atividades</h3><span class="badge">${activity.length}</span></div><div class="event-log">${activity.length?activity.slice(0,100).map(a=>`<div class="event-item"><time>${formatDate(a.createdAt)}</time><div><b>${escapeHTML(a.type.toUpperCase())}</b><br>${escapeHTML(a.message)}</div></div>`).join(''):'<div class="empty-state">Nenhuma atividade registrada.</div>'}</div></article>
  </section>`;
  root.querySelector('#pinForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),pin=String(fd.get('pin')),confirm=String(fd.get('confirm'));if(pin!==confirm)return toast('Os PINs não coincidem.','error');try{await configurePin(pin);await addActivity('seguranca','PIN alterado');toast('PIN alterado.');e.currentTarget.reset();}catch(err){toast(err.message,'error')}};
  root.querySelector('#lockGuardianBtn').onclick=()=>ctx.lock();
  root.querySelector('#exportBtn').onclick=async()=>{const payload=await exportAll();downloadJSON(payload,`assistente-vip-backup-${new Date().toISOString().slice(0,10)}.json`);await addActivity('backup','Backup exportado');toast('Backup exportado.');};
  root.querySelector('#importBtn').onclick=()=>ctx.openImport();
  root.querySelector('#autoLockForm').onsubmit=async e=>{e.preventDefault();const minutes=Number(new FormData(e.currentTarget).get('minutes'));await setSetting('autoLockMinutes',minutes);ctx.setAutoLock(minutes);await addActivity('seguranca',`Bloqueio automático: ${minutes||'manual'}`);toast('Tempo atualizado.');ctx.refresh();};
  root.querySelector('#resetBtn').onclick=async()=>{if(await confirmModal('Apagar todos os dados?','Esta ação remove tudo deste navegador e retorna à configuração inicial. Faça backup antes.','Apagar tudo')){await clearAll();location.reload();}};
}
export async function handleImportFile(file,ctx){
  try{const payload=JSON.parse(await file.text());if(!(await confirmModal('Restaurar backup?','Os dados atuais serão substituídos pelo arquivo selecionado.','Restaurar')))return;await importAll(payload);toast('Backup restaurado. O aplicativo será recarregado.');setTimeout(()=>location.reload(),800);}catch(err){toast(err.message||'Não foi possível importar.','error');}
}
