import {getAll,put,remove,addActivity} from '../db.js';
import {escapeHTML,formatDate,navigate,pageHead,openModal,confirmModal,toast,uid,sanitizeText} from '../ui.js';

export async function renderMemoria(root,ctx,params){
  const all=(await getAll('memories')).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  root.innerHTML=`<section class="page">${pageHead('Memória Viva','Registre ideias, acontecimentos e aprendizados em uma linha do tempo pesquisável.','<button id="newMemoryBtn" class="btn btn-primary">+ Nova memória</button>')}
    <article class="card"><div class="search-row"><label class="field"><span>Pesquisar</span><input id="memorySearch" placeholder="Título, texto, categoria ou etiqueta"></label><label class="field" style="max-width:230px"><span>Categoria</span><select id="memoryCategory"><option value="">Todas</option>${[...new Set(all.map(m=>m.category).filter(Boolean))].map(c=>`<option>${escapeHTML(c)}</option>`).join('')}</select></label></div><div id="memoryList" class="list"></div></article>
  </section>`;
  const draw=()=>{const q=root.querySelector('#memorySearch').value.trim().toLowerCase(),cat=root.querySelector('#memoryCategory').value;const filtered=all.filter(m=>(!cat||m.category===cat)&&(!q||`${m.title} ${m.text} ${m.category} ${(m.tags||[]).join(' ')}`.toLowerCase().includes(q)));root.querySelector('#memoryList').innerHTML=filtered.length?filtered.map(m=>`<article class="list-item"><div style="flex:1"><div class="action-row" style="justify-content:space-between;align-items:center"><b>${escapeHTML(m.title)}</b><span class="badge">${escapeHTML(m.category||'Geral')}</span></div><small>${escapeHTML(m.text.length>180?`${m.text.slice(0,180)}…`:m.text)}</small><small>${formatDate(m.createdAt)}${m.tags?.length?` · ${m.tags.map(t=>`#${escapeHTML(t)}`).join(' ')}`:''}</small></div><div class="action-row"><button class="btn btn-secondary btn-sm" data-view="${m.id}">Ver</button><button class="btn btn-danger btn-sm" data-delete="${m.id}">Excluir</button></div></article>`).join(''):'<div class="empty-state">Nenhuma memória encontrada.</div>';bindList();};
  const bindList=()=>{root.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>viewMemory(all.find(m=>m.id===b.dataset.view)));root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{const m=all.find(x=>x.id===b.dataset.delete);if(await confirmModal('Excluir memória?',`“${m.title}” será removida permanentemente.`,'Excluir')){await remove('memories',m.id);await addActivity('memoria',`Memória excluída: ${m.title}`);toast('Memória excluída.');ctx.refresh();}});};
  root.querySelector('#memorySearch').oninput=draw;root.querySelector('#memoryCategory').onchange=draw;root.querySelector('#newMemoryBtn').onclick=()=>newMemory(ctx);draw();
  if(params?.get('action')==='new') setTimeout(()=>newMemory(ctx),0);
}
function newMemory(ctx){
  const modal=openModal(`<div class="modal-head"><h3>Nova memória</h3><button class="modal-close" type="button">×</button></div><form id="memoryForm" class="form-grid"><label class="field span-2"><span>Título</span><input name="title" maxlength="100" required placeholder="O que deseja lembrar?"></label><label class="field"><span>Categoria</span><select name="category"><option>Ideia</option><option>Acontecimento</option><option>Aprendizado</option><option>Projeto</option><option>Casa</option><option>Finanças</option><option>Trabalho</option><option>Pessoal</option></select></label><label class="field"><span>Etiquetas</span><input name="tags" placeholder="Ex.: carro, importante"></label><label class="field span-2"><span>Registro</span><textarea name="text" required placeholder="Descreva com suas palavras..."></textarea></label><div class="span-2 action-row"><button class="btn btn-primary" type="submit">Salvar memória</button></div></form>`);
  modal.querySelector('#memoryForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const memory={id:uid('memory'),title:sanitizeText(fd.get('title')),category:sanitizeText(fd.get('category')),tags:sanitizeText(fd.get('tags')).split(',').map(x=>x.trim()).filter(Boolean),text:sanitizeText(fd.get('text')),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await put('memories',memory);await addActivity('memoria',`Memória criada: ${memory.title}`);modal.close();toast('Memória registrada.');ctx.refresh();};
}
function viewMemory(m){if(!m)return;openModal(`<div class="modal-head"><div><h3>${escapeHTML(m.title)}</h3><small>${formatDate(m.createdAt)}</small></div><button class="modal-close" type="button">×</button></div><div class="action-row"><span class="badge">${escapeHTML(m.category||'Geral')}</span>${(m.tags||[]).map(t=>`<span class="badge success">#${escapeHTML(t)}</span>`).join('')}</div><p style="white-space:pre-wrap;line-height:1.7">${escapeHTML(m.text)}</p>`);}
