import {getAll,put,remove,addActivity} from '../db.js';
import {escapeHTML,formatDate,pageHead,openModal,confirmModal,toast,uid,sanitizeText,scoreDecision} from '../ui.js';

export async function renderOraculo(root,ctx,params){
  const decisions=(await getAll('decisions')).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  root.innerHTML=`<section class="page">${pageHead('ORÁCULO','Transforme escolhas difíceis em comparações explicáveis. O resultado é apoio, não uma ordem.','<button id="newDecisionBtn" class="btn btn-primary">+ Nova decisão</button>')}
    <div class="grid grid-3"><article class="card stat-card"><span class="stat-label">TOTAL</span><strong class="stat-value">${decisions.length}</strong><small class="stat-label">decisões registradas</small></article><article class="card stat-card"><span class="stat-label">ABERTAS</span><strong class="stat-value">${decisions.filter(d=>d.status!=='concluida').length}</strong><small class="stat-label">aguardando resultado</small></article><article class="card stat-card"><span class="stat-label">CONCLUÍDAS</span><strong class="stat-value">${decisions.filter(d=>d.status==='concluida').length}</strong><small class="stat-label">com escolha registrada</small></article></div>
    <article class="card" style="margin-top:16px"><div class="card-head"><h3>Histórico de decisões</h3><span class="badge success">Análise local</span></div><div class="list">${decisions.length?decisions.map(d=>decisionItem(d)).join(''):'<div class="empty-state">Nenhuma decisão analisada. Crie uma para comparar alternativas.</div>'}</div></article>
  </section>`;
  root.querySelector('#newDecisionBtn').onclick=()=>newDecision(ctx);
  root.querySelectorAll('[data-view-decision]').forEach(b=>b.onclick=()=>viewDecision(decisions.find(d=>d.id===b.dataset.viewDecision),ctx));
  root.querySelectorAll('[data-delete-decision]').forEach(b=>b.onclick=async()=>{const d=decisions.find(x=>x.id===b.dataset.deleteDecision);if(await confirmModal('Excluir decisão?',`A análise “${d.title}” será removida.`,'Excluir')){await remove('decisions',d.id);await addActivity('oraculo',`Decisão excluída: ${d.title}`);toast('Decisão excluída.');ctx.refresh();}});
  if(params?.get('action')==='new') setTimeout(()=>newDecision(ctx),0);
}
function decisionItem(d){const top=[...d.options].sort((a,b)=>b.score-a.score)[0];return `<article class="list-item"><div style="flex:1"><div class="action-row" style="justify-content:space-between;align-items:center"><b>${escapeHTML(d.title)}</b><span class="badge ${d.status==='concluida'?'success':'warning'}">${d.status==='concluida'?'Concluída':'Aberta'}</span></div><small>${escapeHTML(d.context||'Sem contexto adicional.')}</small><small>${formatDate(d.createdAt)} · Melhor pontuação: ${escapeHTML(top?.name||'—')} (${top?.score||0})</small></div><div class="action-row"><button class="btn btn-secondary btn-sm" data-view-decision="${d.id}">Abrir</button><button class="btn btn-danger btn-sm" data-delete-decision="${d.id}">Excluir</button></div></article>`;}
function sliderField(prefix,label,help){return `<label class="field"><span>${label} <small>(${help})</small></span><select name="${prefix}" required>${[1,2,3,4,5].map(n=>`<option value="${n}" ${n===3?'selected':''}>${n}</option>`).join('')}</select></label>`;}
function optionFields(n){return `<article class="card"><h3>Alternativa ${n}</h3><div class="form-grid" style="margin-top:12px"><label class="field span-2"><span>Nome da alternativa</span><input name="name${n}" required placeholder="Ex.: Comprar agora"></label>${sliderField(`benefit${n}`,'Benefício','1 baixo, 5 alto')}${sliderField(`cost${n}`,'Custo ou esforço','1 baixo, 5 alto')}${sliderField(`risk${n}`,'Risco','1 baixo, 5 alto')}${sliderField(`urgency${n}`,'Urgência atendida','1 baixa, 5 alta')}${sliderField(`reversibility${n}`,'Reversibilidade','1 difícil, 5 fácil')}<label class="field"><span>Observação</span><input name="note${n}" placeholder="Ponto importante"></label></div></article>`;}
function newDecision(ctx){
  const modal=openModal(`<div class="modal-head"><h3>Nova análise do ORÁCULO</h3><button class="modal-close" type="button">×</button></div><form id="decisionForm"><div class="form-grid"><label class="field span-2"><span>Decisão</span><input name="title" required maxlength="120" placeholder="Ex.: Vale a pena comprar este equipamento agora?"></label><label class="field span-2"><span>Contexto e prazo</span><textarea name="context" placeholder="Motivação, prazo, impacto e o que acontece se nada for feito."></textarea></label></div><div class="grid grid-2" style="margin-top:14px">${optionFields(1)}${optionFields(2)}</div><div class="action-row" style="margin-top:14px"><button class="btn btn-primary" type="submit">Calcular e salvar</button></div></form><p class="section-note" style="margin-top:14px">Fórmula local: benefício 30%, baixo custo 20%, baixo risco 20%, urgência 15% e reversibilidade 15%.</p>`);
  modal.querySelector('#decisionForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const options=[1,2].map(n=>{const o={name:sanitizeText(fd.get(`name${n}`)),benefit:Number(fd.get(`benefit${n}`)),cost:Number(fd.get(`cost${n}`)),risk:Number(fd.get(`risk${n}`)),urgency:Number(fd.get(`urgency${n}`)),reversibility:Number(fd.get(`reversibility${n}`)),note:sanitizeText(fd.get(`note${n}`))};o.score=scoreDecision(o);return o;});const d={id:uid('decision'),title:sanitizeText(fd.get('title')),context:sanitizeText(fd.get('context')),options,status:'aberta',choice:null,review:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await put('decisions',d);await addActivity('oraculo',`Decisão criada: ${d.title}`);modal.close();toast('Análise salva.');viewDecision(d,ctx);};
}
function viewDecision(d,ctx){if(!d)return;const sorted=[...d.options].sort((a,b)=>b.score-a.score),winner=sorted[0],loser=sorted[1];const modal=openModal(`<div class="modal-head"><div><h3>${escapeHTML(d.title)}</h3><small>${formatDate(d.createdAt)}</small></div><button class="modal-close" type="button">×</button></div>${d.context?`<p>${escapeHTML(d.context)}</p>`:''}<div class="score-panel">${sorted.map(o=>`<div class="score-row"><span>${escapeHTML(o.name)}</span><div class="score-bar"><i style="width:${o.score}%"></i></div><strong>${o.score}</strong></div>`).join('')}</div><div class="decision-winner" style="margin-top:16px"><h4>Melhor pontuação atual: ${escapeHTML(winner.name)}</h4><p>Vantagem de ${Math.max(0,winner.score-loser.score)} ponto(s). Revise os dados antes de decidir.</p></div><div class="grid grid-2" style="margin-top:14px">${sorted.map(o=>`<article class="card"><h3>${escapeHTML(o.name)}</h3><div class="record-grid" style="margin-top:10px"><div class="kv"><small>Benefício</small><strong>${o.benefit}/5</strong></div><div class="kv"><small>Custo</small><strong>${o.cost}/5</strong></div><div class="kv"><small>Risco</small><strong>${o.risk}/5</strong></div><div class="kv"><small>Urgência</small><strong>${o.urgency}/5</strong></div><div class="kv"><small>Reversibilidade</small><strong>${o.reversibility}/5</strong></div><div class="kv"><small>Observação</small><strong>${escapeHTML(o.note||'—')}</strong></div></div></article>`).join('')}</div><article class="card" style="margin-top:14px"><h3>Advogado do contrário</h3><p>Mesmo que <strong>${escapeHTML(winner.name)}</strong> tenha vencido, confirme se a pontuação não foi influenciada por urgência emocional, estimativa otimista de benefício ou subestimação de custo e risco. A alternativa <strong>${escapeHTML(loser.name)}</strong> pode ser melhor se preservar mais recursos ou tornar a decisão mais reversível.</p></article><form id="decisionCloseForm" class="form-grid" style="margin-top:14px"><label class="field"><span>Escolha realizada</span><select name="choice"><option value="">Ainda não decidi</option>${d.options.map(o=>`<option ${d.choice===o.name?'selected':''}>${escapeHTML(o.name)}</option>`).join('')}</select></label><label class="field"><span>Resultado ou observação</span><input name="review" value="${escapeHTML(d.review||'')}" placeholder="Ex.: decidi aguardar 30 dias"></label><div class="span-2 action-row"><button class="btn btn-primary" type="submit">Atualizar decisão</button></div></form>`);
  modal.querySelector('#decisionCloseForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);d.choice=sanitizeText(fd.get('choice'))||null;d.review=sanitizeText(fd.get('review'));d.status=d.choice?'concluida':'aberta';d.updatedAt=new Date().toISOString();await put('decisions',d);await addActivity('oraculo',`Decisão atualizada: ${d.title}`);modal.close();toast('Decisão atualizada.');ctx.refresh();};
}
